name: Add Unresolvable Domains
run-name: Add [ DoH + DoT + Proxy + VPN + Tor ] unresolvable domains
on:
  workflow_run:
    workflows: [Domains to IP4s, Domains to IP6s]
    types: [completed]
    branches: [master]

jobs:
  update:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Delayed re-pull (5sec) to get new unresolvables by domain2ip
        run: sleep 5; git pull
      - name: Update Lists
        run:  |
          bash scripts/add-unresolvable.sh
      - name: Get current date
        id: get-date
        run: echo "date=$(date +'%Y-%m-%d - %H:%M:%S')" >> $GITHUB_OUTPUT
      - name: Upload Stuff to GitHub via https://github.com/stefanzweifel/git-auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: './unresolvable.txt'
          disable_globbing: true
          status_options: '--untracked-files=no'
          commit_message: Add unresolvable domains - ${{ steps.get-date.outputs.date }}
