name: Update Unresolvable Domains Queue1
run-name: updating [ DoH + DoT + Proxy + VPN + Tor ] unresolvable domains
on:
  schedule:
    - cron: "00 15 * * *" # UTC

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Update Lists
        run:  |
          bash scripts/update-unresolvable.sh 1
      - name: Get current date
        id: get-date
        run: echo "date=$(date +'%Y-%m-%d - %H:%M:%S')" >> $GITHUB_OUTPUT
      - name: Upload Stuff to GitHub via https://github.com/stefanzweifel/git-auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: './unresolvable.txt ./unresolvable_perm.txt'
          disable_globbing: true
          status_options: '--untracked-files=no'
          commit_message: Update unresolvable domains - Q1 - ${{ steps.get-date.outputs.date }}
