name: Domains to IPs
run-name: converting DoH + DoT + Proxy + VPN domains to IPv4+IPv6
on:
  push:
    branches:
      - master
  schedule:
    - cron: "00 03 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Delayed re-pull (2min)
        run: sleep 120; git pull
      - name: Get IPv4
        run:  |
          ipv4=(); while read -r dns2ip_v4; do \
              dig4="$(dig "${dns2ip_v4}" in a -4 +short +ignore +notcp +time=10 +tries=10 +retry=10 2>/dev/null || true)"; \
              if [ -n "${dig4}" ] && ! echo "${dig4}" | grep -q "^0\.0\.0\.0\|^127\.0\.0\.1$\|^;"; then ipv4+=( "${dig4}" ); fi \
          done < <(cat black.txt | grep -vE "^$(sed -e '/^#.*/d' -e 's/\s*#.*$//g' -e 's/[[:space:]]//g' white.txt)$"); \
          if [ "$(echo "${ipv4[*]}" | sed "s/ /\n/g" | grep -coE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b" | sort -Vu)" -ge 100 ]; then \
              true > black.ipv4; for ip in "${ipv4[@]}"; do echo "${ip}" >> black-tmp.ipv4; done; fi; \
          grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b" black-tmp.ipv4 | sort -Vu | sed '/^$/d' > black.ipv4; rm -f black-tmp.ipv4
      - name: Get IPv6
        run:  |
          ipv6=(); while read -r dns2ip_v6; do \
              dig6="$(dig "${dns2ip_v6}" in aaaa -4 +short +ignore +notcp +time=10 +tries=10 +retry=10 2>/dev/null || true)"; \
              if [ -n "${dig6}" ] && ! echo "${dig6}" | grep -q "^::$\|^::1$\|^53:$\|^;"; then ipv6+=( "${dig6}" ); fi \
          done < <(cat black.txt | grep -vE "^$(sed -e '/^#.*/d' -e 's/\s*#.*$//g' -e 's/[[:space:]]//g' white.txt)$"); \
          if [ "$(echo "${ipv6[*]}" | sed "s/ /\n/g" | grep -coE "\b([a-f0-9:]+:+)+[a-f0-9]+\b" | sort -Vu)" -ge 100 ]; then \
              true > black.ipv6; for ip in "${ipv6[@]}"; do echo "${ip}" >> black-tmp.ipv6; done; fi; \
          grep -oE "\b([a-f0-9:]+:+)+[a-f0-9]+\b" black-tmp.ipv6 | sort -Vu | sed '/^$/d' > black.ipv6; rm -f black-tmp.ipv6
      - name: Get current date
        id: get-date
        run: echo "date=$(date +'%Y-%m-%d - %H:%M:%S')" >> $GITHUB_OUTPUT
      - name: Upload Stuff to GitHub via https://github.com/stefanzweifel/git-auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: './black*.ipv4 ./black*.ipv6'
          disable_globbing: false
          commit_message: Update domains2ip - ${{ steps.get-date.outputs.date }}
