name: Update Domains
run-name: updating [ DoH + DoT + Proxy + VPN + Tor ] domains
on:
  push:
    branches:
      - master
  schedule:
    - cron: "00 22 * * *" # UTC

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@master
        with:
          fetch-depth: 2
      - name: Update Lists
        run:  |
          bash scripts/update-domains.sh
      - name: Get current date
        id: get-date
        run: echo "date=$(date +'%Y-%m-%d - %H:%M:%S')" >> $GITHUB_OUTPUT
      - name: Upload Stuff to GitHub via https://github.com/stefanzweifel/git-auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: './black.txt'
          disable_globbing: true
          commit_message: Update domains - ${{ steps.get-date.outputs.date }}
