name: Domains to IP6s
run-name: converting [ DoH + DoT + Proxy + VPN + Tor ] domains to IPv6
on:
  workflow_run:
    workflows: [Update Domains]
    types: [completed]
    branches: [master]

jobs:
  update:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Delayed re-pull (5sec) to get new domains after push
        run: sleep 5; git pull
      - name: Get IPv6 # Exclude: https://www.iana.org/assignments/iana-ipv6-special-registry/iana-ipv6-special-registry.xhtml
        run:  |
          bash scripts/update-domain2ips.sh IPv6
      - name: Get current date
        id: get-date
        run: echo "date=$(date +'%Y-%m-%d - %H:%M:%S')" >> $GITHUB_OUTPUT
      - name: Upload Stuff to GitHub via https://github.com/stefanzweifel/git-auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: './black.ipv6 ./unresolvable.ipv6'
          disable_globbing: true
          status_options: '--untracked-files=no'
          commit_message: Update domains2ip - IPv6 - ${{ steps.get-date.outputs.date }}
