name: Domains to IP6s
run-name: converting [ DoH + DoT + Proxy + VPN + Tor ] domains to IPv6
on:
  push:
    branches:
      - master
  schedule:
    - cron: "05 01 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@master
        with:
          fetch-depth: 2
      - name: Get IPv6 # Exclude: https://www.iana.org/assignments/iana-ipv6-special-registry/iana-ipv6-special-registry.xhtml
        run:  |
          bash scripts/update-domain2ips.sh IPv6
      - name: Re-pull before push to get possible new black.ipv4
        run: git pull
      - name: Get current date
        id: get-date
        run: echo "date=$(date +'%Y-%m-%d - %H:%M:%S')" >> $GITHUB_OUTPUT
      - name: Upload Stuff to GitHub via https://github.com/stefanzweifel/git-auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: './black.ipv6'
          disable_globbing: true
          commit_message: Update domains2ip - IPv6 - ${{ steps.get-date.outputs.date }}
